version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "jquery"
  ]

[[analyzers]]
name = "sql"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"