name: Prettify Code

on:
  push:
    branches:
      - main

jobs:
  prettify-code:
    name: Prettify Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: actionsx/prettier
        uses: actionsx/prettier@v2
        with:
          args: "--write ."
